# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
#
# Nicole Narr <narrn@student.ethz.ch>
# Christopher Reinwardt <creinwar@student.ethz.ch>
# Cyril Koenig <cykoenig@iis.ee.ethz.ch>
# Paul Scheffler <paulsc@iis.ee.ethz.ch>

#############
# Sys Clock #
#############

# 100 MHz input clock
set SYS_TCK 10
create_clock -period $SYS_TCK -name sys_clk [get_ports sys_clk]


# SoC clock is generated by clock wizard and its constraints
set SOC_TCK 50.0                //->sửa lại clkwiz
set soc_clk [get_clocks -of_objects [get_pins i_clkwiz/clk_out1] //clk20M

<<<<<<<< HEAD:xilinx/src/nexys4_ddr.xdc

========
>>>>>>>> aaa1214 (Sua constrain xpr):xilinx/src/nexys-a7-100t.xdc
############
# Switches #
############

set_input_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [ \
    get_ports {gpio_i* fan_sw* fetch_en_i}]
set_input_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [ \
    get_ports {gpio_i* f'''''''an_sw* fetch_en_i}]

set_output_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [get_ports fan_pwm]
set_output_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [get_ports fan_pwm]

set_max_delay [expr { 2 * $SOC_TCK }] -from [get_ports {gpio_i* fan_sw* fetch_en_i}]
set_false_path -hold -from [get_ports {gpio_i* fan_sw* fetch_en_i}]

set_max_delay [expr { 2 * $SOC_TCK }] -to [get_ports fan_pwm]
set_false_path -hold -to [get_ports fan_pwm]

# LEDs
set_output_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [get_ports gpio_o]
set_output_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [get_ports gpio_o]
<<<<<<<< HEAD:xilinx/src/nexys4_ddr.xdc

========
>>>>>>>> aaa1214 (Sua constrain xpr):xilinx/src/nexys-a7-100t.xdc

###############
# Assign Pins #
###############

# tclint-disable line-length, spacing

## Clock Signal
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { sys_clk }]; #IO_L12P_T1_MRCC_35 Sch=clk100mhz
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports {sys_clk}];

## Buttons
set_property -dict { PACKAGE_PIN R19   IOSTANDARD LVCMOS33 } [get_ports { sys_resetn }]; #IO_0_14 Sch=cpu_resetn

## Switches
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS12 } [get_ports { gpio_i[0] }]; #IO_0_17 Sch=sw[0]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS12 } [get_ports { gpio_i[1] }]; #IO_25_16 Sch=sw[1]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS12 } [get_ports { gpio_i[2] }]; #IO_L19P_T3_16 Sch=sw[2]
set_property -dict { PACKAGE_PIN R15   IOSTANDARD LVCMOS12 } [get_ports { gpio_i[3] }]; #IO_L6P_T0_17 Sch=sw[3]
set_property -dict { PACKAGE_PIN R17   IOSTANDARD LVCMOS12 } [get_ports { fan_sw[0] }]; #IO_L19P_T3_A22_15 Sch=sw[4]
set_property -dict { PACKAGE_PIN T18   IOSTANDARD LVCMOS12 } [get_ports { fan_sw[1] }]; #IO_25_15 Sch=sw[5]
set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33 } [get_ports { fan_sw[2] }]; #IO_L10P_T1_D14_14 Sch=sw[6]
set_property -dict { PACKAGE_PIN R13   IOSTANDARD LVCMOS33 } [get_ports { fetch_en_i }]; #IO_L8P_T1_D11_14 Sch=sw[7]



## LEDs
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[0] }]; #IO_L11N_T1_SRCC_14 Sch=led[0]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[1] }]; #IO_L19P_T3_A10_D26_14 Sch=led[1]
set_property -dict { PACKAGE_PIN J13   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[2] }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=led[2]
set_property -dict { PACKAGE_PIN N14   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[3] }]; #IO_L15P_T2_DQS_RDWR_B_14 Sch=led[3]
# set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { led[4] }]; #IO_L19N_T3_A09_D25_VREF_14 Sch=led[4]
# set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports { led[5] }]; #IO_L16P_T2_CSI_B_14 Sch=led[5]
# set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports { led[6] }]; #IO_L20N_T3_A07_D23_14 Sch=led[6]

## UART
set_property -dict { PACKAGE_PIN D4   IOSTANDARD LVCMOS33 } [get_ports { uart_tx_o }]; #IO_L1P_T0_12 Sch=uart_rx_out
set_property -dict { PACKAGE_PIN C4   IOSTANDARD LVCMOS33 } [get_ports { uart_rx_i }]; #IO_0_12 Sch=uart_tx_in

## DPTI
# Note: DPTI and DSPI constraints cannot be used in the same design, as they share pins.
<<<<<<<< HEAD:xilinx/src/nexys4_ddr.xdc
# set_property -dict { PACKAGE_PIN AD27  IOSTANDARD LVCMOS33 } [get_ports { jtag_tck_i }]; #IO_L11P_T1_SRCC_13 Sch=prog_d0/sck
# set_property -dict { PACKAGE_PIN W27   IOSTANDARD LVCMOS33 } [get_ports { jtag_tdi_i }]; #IO_L2P_T0_13 Sch=prog_d1/mosi
# set_property -dict { PACKAGE_PIN W28   IOSTANDARD LVCMOS33 } [get_ports { jtag_tdo_o }]; #IO_L2N_T0_13 Sch=prog_d2/miso
# set_property -dict { PACKAGE_PIN W29   IOSTANDARD LVCMOS33 } [get_ports { jtag_tms_i }]; #IO_L4P_T0_13 Sch=prog_d3/ss
# set_property -dict { PACKAGE_PIN Y29   set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { status_o }]; #IO_L20P_T3_A08_D24_14 Sch=led[7]
IOSTANDARD LVCMOS33 } [get_ports { jtag_trst_ni }]; #IO_L4N_T0_13 Sch=prog_d[4]
========
set_property -dict { PACKAGE_PIN C17   IOSTANDARD LVCMOS33 } [get_ports { jtag_tck_i }]; #IO_L11P_T1_SRCC_13 Sch=ja1
set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { jtag_tdi_i }]; #IO_L2P_T0_13 Sch=ja2
set_property -dict { PACKAGE_PIN E18   IOSTANDARD LVCMOS33 } [get_ports { jtag_tdo_o }]; #IO_L2N_T0_13 Sch=ja3
set_property -dict { PACKAGE_PIN G17   IOSTANDARD LVCMOS33 } [get_ports { jtag_tms_i }]; #IO_L4P_T0_13 Sch=ja4
set_property -dict { PACKAGE_PIN D17   IOSTANDARD LVCMOS33 } [get_ports { jtag_trst_ni }]; #IO_L4N_T0_13 Sch=ja5
>>>>>>>> aaa1214 (Sua constrain xpr):xilinx/src/nexys-a7-100t.xdc

# tclint-enable line-length, spacing
